version: '2'
services:
  mysql_db:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - SERVER_PORT=3306
    ports:
        - "3306:3306"

  rest:
    image: antonppavlov/iwanttoeat
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/iwanttoeat?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=8080
    links:
      - mysql_db
    ports:
      - "8080:8080"
